const regions = ["BRETAGNE","PAYS-DE-LA-LOIRE","NORMANDIE","AUVERGNE/RHÔNE-ALPES","ÎLE-DE-FRANCE","OCCITANIE","HAUTS-DE-FRANCE","CENTRE-VAL-DE-LOIRE","AUVERGNE-RHÔNE-ALPES","BOURGOGNE-FRANCHE-COMTÉ","NOUVELLE-AQUITAINE","PROVENCE-ALPES-CÔTE D'AZUR","GRAND EST"]; 

export default regions;